### ISSUE TITLE
Parsing Issue when using black's exclude format

### ISSUE THREAD

**Issue by stvnksslr** [csachs/pyproject-flake8#1]
I will be taking a crack at a PR on this in a little bit, just want to document the issue, as this is a brand new project and I don't expect support with an alpha designation.

Thank you for getting the ball rolling on a minimal wrapper for pyproject support was just thinking of doing something the other day.

## ISSUE: 
TOML parser seems to fail on some of the more verbose syntax that the black tool has introduced into its code block

example from their documents https://black.readthedocs.io/en/stable/pyproject_toml.html#configuration-format

```toml
[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )
)
'''
```

this results in a parsing error 
```
Unable to parse config file: Source contains parsing errors: '/PATH/TO/PROJECT_ROOT/pyproject.toml'
	[line 50]: '(\n'
	[line 64]: ')\n'
	[line 65]: "'''"
```

**Comment by csachs** [comment]
`pyproject-flake8` uses the same toml parser as black ( http://pypi.org/project/toml ), therefore both should work with the same `pyproject.toml` files; are you running them with the same version? Can you post steps to reproduce the issue?
Saving the `pyproject.toml` in an directory, then running either `black` or `pflake8` yields no errors for me.

**Comment by stvnksslr** [comment]
## Project
https://github.com/stvnksslr/dataslate-parser/blob/main/pyproject.toml

## Steps
* `poetry install` or `pip install -r requirents-dev.txt`
* `pflake8`

**Comment by csachs** [comment]
Thank you @stvnksslr , now I could reproduce the problem (and thank you in general for your interest in the project!)
The problem stems from one of pyflake's plugins you're using. If you haven't started working on it, I can fix it quickly, otherwise I can wait for your PR.

**Comment by stvnksslr** [comment]
Ah thanks for pointing me in the right direction!

Narrowed it down to the flake8-bandit library being the problem, I have not gotten started on a fix yet.

**Comment by csachs** [comment]
@stvnksslr if you haven't started, I'll quickly push a fix. Could you please try the current main version to check if the problem is solved?
`flake8-bandit` instantiated its own configuration parsing independent of `flake8`, using a `configparser.ConfigParser` instead of a `configparser.RawConfigParser` as `flake8`, which was monkeypatched by `pyproject-flake8`, so it tried to parse the `pyproject.toml` as a normal configuration file. The behavior is mitigated by monkeypatching all classes now.
Thanks for reporting this issue!

**Comment by stvnksslr** [comment]
Checked out the latest commit and can confirm the issue looks to be fixed.

thank you!

**Comment by csachs** [comment]
I've just pushed a new version to PyPI. Thanks again for reporting.
