### ISSUE TITLE
Not compatible with flake8 5.0

### ISSUE THREAD

**Issue by NeilGirdhar** [csachs/pyproject-flake8#13]
```
  File "/Users/neil/Library/Caches/pypoetry/virtualenvs/generators-0uytuYoH-py3.10/lib/python3.10/site-packages/pflake8/__init__.py", line 54, in <module>
    class ModifiedConfigFileFinder(flake8.options.config.ConfigFileFinder):
AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
```

**Comment by schinckel** [comment]
Looks like this class went away: instead the files that are checked are hard-coded inside a function:

https://github.com/PyCQA/flake8/blame/91a7fa9ac360be7f43b1325875cf5bf4fe89e380/src/flake8/options/config.py#L31

One alternative could be to use something like `patchy` to change this.

**Comment by NeilGirdhar** [comment]
@schinckel I don't know patchy.  Would it be possible to simply override
```python
def _find_config_file(path: str) -> Optional[str]:
```

**Comment by NeilGirdhar** [comment]
@schinckel That's a good idea!

**Comment by wieczorek1990** [comment]
Please see here:
https://github.com/PyCQA/flake8/pull/1634

**Comment by wieczorek1990** [comment]
And here:
https://github.com/csachs/pyproject-flake8/pull/14

**Comment by wieczorek1990** [comment]
For me this is unnamed constant. But sure it’s monkey patchable this way.

W dniu pon., 1.08.2022 o 15:56 Neil Girdhar ***@***.***>
napisał(a):

**Comment by wieczorek1990** [comment]
Updated the pull request #14 , so that it's compatible with flake8 version 5.

**Comment by jaklan** [comment]
@NeilGirdhar

> It seems like Anthony is going out of his way to interfere with this project.

The Anthony's [fight against `toml`](https://github.com/PyCQA/flake8/issues/234) is one of the must frustrating things I have ever seen in the Python community. One guy doesn't like the agreed standard, so he does everything to sabotage its adoption... Anyway, I really cross my fingers for resolving the issue, so we could stay with `pyproject.toml`-only configs again!

**Comment by eggplants** [comment]
Please create new release... I would like to use this package including the fixture in `pre-commit` without `rev: main`.
