### ISSUE TITLE
pflake8 doesn't propagate the flake8 exit code when used as a runnable module

### ISSUE THREAD

**Issue by evertrol** [csachs/pyproject-flake8#19]
If I run 
```
python -m pflake8 nonexisting.py 2>1 > /dev/null
echo $?
```
the exit code is 0. (This is tested on macOS, zsh).

For comparison, the following variants all return `1` as exit code
```
pflake8 nonexisting.py 2>1 > /dev/null
python -m flake8 nonexisting.py 2>1 > /dev/null
flake8 nonexisting.py 2>1 > /dev/null
```

I would definitely expect `python -m pflake8 nonexisting.py` to also have a non-zero exit code (exit code of `1`, in fact).

**Comment by csachs** [comment]
Oups, completely missed that, should be fixed now.

**Comment by evertrol** [comment]
Thanks. I can confirm this works now.
And just in time for 6.0.0, I see.
