### ISSUE TITLE
Support flake8 6.1.0?

### ISSUE THREAD

**Issue by tueda** [csachs/pyproject-flake8#27]
flake8 6.1.0 has been released: https://flake8.pycqa.org/en/latest/release-notes/6.1.0.html

Will `pyproject-flake8` support the minor version `6.1.0` in the sense of allowing the users to use `pip install pyproject-flake8==6.1.0`?

Or should the users use `pip install pyproject-flake8==6.0.0a1` (which is compatible with `flake8>=6.0.0`)?

**Comment by csachs** [comment]
Sorry for the delay, 6.1.0 and 6.1.0a are out.
